Repository gardener/oidc-webhook-authenticator, pull requests merged in 2021-11, with the labels that each got.

#40 Remove unused configz handler
  cmd/oidc-webhook-authenticator/app/oidc_webhook_authenticator.go
Labels: kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/xs

#38 Adds the ability to configure api audiences flag
  charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml
  charts/oidc-webhook-authenticator/values.yaml
  cmd/oidc-webhook-authenticator/app/oidc_webhook_authenticator.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#43 Extend chart installation configuration
  charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml
  charts/oidc-webhook-authenticator/charts/runtime/templates/role-binding-auth-delegator.yaml
  charts/oidc-webhook-authenticator/charts/runtime/templates/role-binding-extension-apiserver.yaml
  charts/oidc-webhook-authenticator/charts/runtime/templates/secret-auth-kubeconfig.yaml
  charts/oidc-webhook-authenticator/charts/runtime/templates/secret-kubeconfig.yaml
  charts/oidc-webhook-authenticator/values.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#39 Fix the initialization of defaulting and validating webhooks
  charts/oidc-webhook-authenticator/charts/application/templates/validating-webhook-configuration.yaml
  charts/oidc-webhook-authenticator/values.yaml
  cmd/oidc-webhook-authenticator/app/oidc_webhook_authenticator.go
Labels: area/quality, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/s

#50 Remove apt-get update when tests are executed by the CI/CD
  .ci/test
Labels: kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/xs

#47 Configure slack notifications on release
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#48 Move delegator bindings to application part of chart installation
  charts/oidc-webhook-authenticator/charts/application/templates/role-binding-auth-delegator.yaml
  charts/oidc-webhook-authenticator/charts/application/templates/role-binding-extension-apiserver.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#49 Adds the ability to configure hpa
  charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml
  charts/oidc-webhook-authenticator/charts/runtime/templates/hpa.yaml
  charts/oidc-webhook-authenticator/values.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/s

#46 Add validation for malicious prefixes
  apis/authentication/v1alpha1/openidconnect_types.go
  apis/authentication/v1alpha1/openidconnect_webhook.go
  apis/authentication/v1alpha1/openidconnect_webhook_test.go
  controllers/authentication/openidconnect_controller.go
Labels: area/security, reviewed/lgtm, needs/ok-to-test, size/m

#52 Adds the ability to configure user for the virtual garden bindings
  charts/oidc-webhook-authenticator/charts/application/templates/rbac.yaml
  charts/oidc-webhook-authenticator/charts/application/templates/role-binding-auth-delegator.yaml
  charts/oidc-webhook-authenticator/charts/application/templates/role-binding-extension-apiserver.yaml
  charts/oidc-webhook-authenticator/charts/application/templates/serviceaccount.yaml
  charts/oidc-webhook-authenticator/values.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#45 Refactor of the integration tests setup
  hack/local/run-tests.sh
  test/integration/ca/ca.crt
  test/integration/ca/ca.key
  test/integration/cert-utils/utils.go
  test/integration/config/webhook-kubeconfig.yaml
  test/integration/env/aggregator.go
  test/integration/env/environment.go
  test/integration/env/oidc_webhook_server.go
  test/integration/id-certs/tls.crt
  test/integration/id-certs/tls.key
  test/integration/integration_suite_test.go
  test/integration/integration_test.go
  test/integration/mock/identityserver.go
  test/integration/token-gen-keys/gen.key
  test/integration/token-gen-keys/gen.pem
Labels: area/testing, kind/enhancement, kind/test, reviewed/lgtm, needs/ok-to-test, size/xl

#54 Stop defaulting username and groups claims
  Makefile
  apis/authentication/v1alpha1/openidconnect_types.go
  charts/oidc-webhook-authenticator/charts/application/templates/authentication.gardener.cloud_openidconnects.yaml
  config/crd/bases/authentication.gardener.cloud_openidconnects.yaml
  dev.Dockerfile
  test/integration/integration_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#55 Add test for removing existing groups claim from oidc resource
  test/integration/integration_test.go
Labels: area/quality, area/testing, reviewed/lgtm, needs/ok-to-test, size/s

#56 Update README so it includes link with built docker images
  README.md
Labels: area/documentation, reviewed/lgtm, needs/ok-to-test, size/xs

#59 Add HSTS Header to mock identity server responses
  test/integration/mock/identityserver.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
