Repository gardener/oidc-webhook-authenticator, pull requests merged in 2022-01, with the labels that each got.

#63 Go version upgraded to 1.17.6
  Dockerfile
  apis/authentication/v1alpha1/zz_generated.deepcopy.go
  dev.Dockerfile
Labels: area/open-source, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#64 Fix unability to disable automount of sa tokens
  charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml
Labels: kind/bug, reviewed/lgtm, needs/ok-to-test, size/xs

#65 Use the default OCI image builder
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
