Repository gardener/oidc-webhook-authenticator, pull requests merged in 2023-10, with the labels that each got.

#128 Implement extra claims handling
  Makefile
  apis/authentication/v1alpha1/openidconnect_types.go
  apis/authentication/v1alpha1/openidconnect_webhook.go
  apis/authentication/v1alpha1/openidconnect_webhook_test.go
  apis/authentication/v1alpha1/zz_generated.deepcopy.go
  charts/oidc-webhook-authenticator/charts/application/templates/authentication.gardener.cloud_openidconnects.yaml
  config/crd/bases/authentication.gardener.cloud_openidconnects.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/authentication/openidconnect_controller.go
  controllers/authentication/openidconnect_controller_test.go
  controllers/authentication/utils.go
  dev.Dockerfile
  test/integration/integration_test.go
Labels: reviewed/ok-to-test, needs/ok-to-test, needs/changes, size/l

#132 upgrade go to version 1.21.2
  Dockerfile
  dev.Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#133 Implement support for imagePullSecrets
  charts/oidc-webhook-authenticator/charts/runtime/templates/deployment.yaml
  charts/oidc-webhook-authenticator/charts/runtime/values.yaml
  charts/oidc-webhook-authenticator/values.yaml
Labels: needs/ok-to-test, size/xs

#134 Update golang to 1.21.3
  Dockerfile
  dev.Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
