Repository gardener/oidc-webhook-authenticator, pull requests merged in 2024-01, with the labels that each got.

#143 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  README.md
  charts/oidc-webhook-authenticator/charts/runtime/values.yaml
  charts/oidc-webhook-authenticator/values.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, needs/ok-to-test, size/xs

#145 Update go, debian and k8s dependencies
  Dockerfile
  dev.Dockerfile
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#146 Update go to version 1.21.6
  Dockerfile
  dev.Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
